# --- Servicio RTMP/HLS ---
FROM alfg/nginx-rtmp:latest

# Carpeta de segmentos (usa Disk en Render montado en /var/data)
ENV HLS_DIR=/var/data/hls

# Copiamos configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf

# Crear carpeta HLS en arranque del contenedor (por si no existe)
RUN mkdir -p ${HLS_DIR} && chown -R nginx:nginx ${HLS_DIR}

EXPOSE 1935 8080
CMD ["nginx", "-g", "daemon off;"]
