; --- Subidas de archivos ---
file_uploads = On

; Tamaños (POST debe ser > upload_max_filesize)
upload_max_filesize = 10M
post_max_size = 12M
max_file_uploads = 20

; Rendimiento / límites
memory_limit = 256M
max_execution_time = 60
max_input_time = 60

; Seguridad / logs
expose_php = Off
display_errors = Off
log_errors = On
error_reporting = E_ALL

; (Opcional) mejora compresión en respuestas de texto
zlib.output_compression = On

; (Opcional) opcache en producción (la imagen php:8.1-apache ya lo trae)
opcache.enable=1
opcache.validate_timestamps=1
opcache.revalidate_freq=2
